apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: ghcr.io/cdktf/cli
test:
  - image: ghcr.io/cdktf/cli
    structureTests:
      - ./test/structure_tests.yaml
profiles:
- name: local
  build:
    artifacts:
    - image: ghcr.io/cdktf/cli
      docker:
        buildArgs:
          TF_VERSION: 0.14.5
          CDKTF_VERSION: 0.1.0
    local:  
      useBuildkit: true
